"""The successful path of M2, frozen before this lane touched it.

`baseline_m2_runs.json` is the serialised result of the runs below, generated
from `0b86e96` — the commit this branch left from — and never regenerated by a
test. That is the whole point of it: a fixture a test can rewrite proves nothing
about compatibility, it only records what the code does today.

The comparison is deliberately asymmetric. Every key that existed at M2 must
still be present, in the same position, with the same value. Keys this lane
added are listed in `ADDITIVE_STEP_KEYS` and stripped before the comparison, so
a reader can see the exact size of the additive surface in one place instead of
inferring it from a diff.

Regenerating the baseline is a deliberate act, not a test side effect:

    python -c "import pathlib,sys; sys.path[:0]=['src','tests']; \
from reliability.test_compatibility import write_baseline; write_baseline()"

Doing it on this branch would invalidate the evidence. It exists for the day a
milestone intentionally changes the successful path and says so in its report.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Final

import pytest

from agentic_rag.agent import ResearchState, ResearchStatus, run_research
from agentic_rag.tools import FakeRetrievalBackend, RetrieveTool

BASELINE_PATH: Final = Path(__file__).with_name("baseline_m2_runs.json")

ADDITIVE_STEP_KEYS: Final = ("failure",)
"""Keys added to a step record by this lane. Absent from the M2 baseline."""

ANSWERABLE: Final = "What does hybrid retrieval buy over dense retrieval alone?"
COMPOUND: Final = (
    "How does chunking work and what happens when a citation marker resolves to nothing "
    "then how does refusal work?"
)
OFF_CORPUS: Final = "What were the quarterly revenues in Patagonia?"
THIN: Final = "How does chunking work?"
UNICODE: Final = "¿Qué hace el reranking — 再ランキング — sobre la lista corta?"
LONG: Final = (
    "Explain how hybrid retrieval fuses a dense ranking and a sparse ranking and then "
    "explain what a reranker adds on top of that shortlist and then explain how a citation "
    "marker is resolved back to the chunk it was retrieved from"
)

BASELINE_CASES: Final[tuple[dict[str, Any], ...]] = (
    {"name": "answerable-default", "question": ANSWERABLE, "max_steps": 4, "top_k": 5},
    {"name": "answerable-narrow", "question": ANSWERABLE, "max_steps": 4, "top_k": 1},
    {"name": "compound-plan", "question": COMPOUND, "max_steps": 4, "top_k": 5},
    {"name": "compound-one-step", "question": COMPOUND, "max_steps": 1, "top_k": 5},
    {"name": "off-corpus-refusal", "question": OFF_CORPUS, "max_steps": 3, "top_k": 5},
    {"name": "thin-budget-exhausted", "question": THIN, "max_steps": 1, "top_k": 1},
    {"name": "thin-insufficient", "question": THIN, "max_steps": 5, "top_k": 5},
    {"name": "unicode-question", "question": UNICODE, "max_steps": 3, "top_k": 5},
    {"name": "long-compound", "question": LONG, "max_steps": 20, "top_k": 5},
)
"""One entry per successful-path shape M2 could produce. No tool failures here."""


def run_case(case: dict[str, Any]) -> ResearchState:
    return run_research(
        case["question"],
        tool=RetrieveTool(FakeRetrievalBackend()),
        max_steps=case["max_steps"],
        top_k=case["top_k"],
    )


def normalize(state: ResearchState) -> dict[str, Any]:
    """Return the run's JSON dump with this lane's additive keys removed."""
    dump = state.model_dump(mode="json")
    for step in dump["steps"]:
        for key in ADDITIVE_STEP_KEYS:
            step.pop(key, None)
    return dump


def write_baseline() -> None:
    payload = {case["name"]: normalize(run_case(case)) for case in BASELINE_CASES}
    BASELINE_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", "utf-8")


def load_baseline() -> dict[str, Any]:
    loaded: dict[str, Any] = json.loads(BASELINE_PATH.read_text("utf-8"))
    return loaded


@pytest.mark.parametrize("case", BASELINE_CASES, ids=lambda case: str(case["name"]))
def test_a_successful_run_still_serialises_exactly_as_m2_did(case: dict[str, Any]) -> None:
    expected = load_baseline()[case["name"]]

    assert normalize(run_case(case)) == expected


@pytest.mark.parametrize("case", BASELINE_CASES, ids=lambda case: str(case["name"]))
def test_the_field_order_of_a_successful_dump_is_unchanged(case: dict[str, Any]) -> None:
    expected = load_baseline()[case["name"]]
    actual = normalize(run_case(case))

    assert list(actual) == list(expected)
    for index, step in enumerate(actual["steps"]):
        assert list(step) == list(expected["steps"][index])
    for index, event in enumerate(actual["trace"]):
        assert list(event) == list(expected["trace"][index])


@pytest.mark.parametrize("case", BASELINE_CASES, ids=lambda case: str(case["name"]))
def test_a_run_without_a_tool_failure_records_no_new_trace_event(case: dict[str, Any]) -> None:
    expected = load_baseline()[case["name"]]
    actual = normalize(run_case(case))

    assert [event["event"] for event in actual["trace"]] == [
        event["event"] for event in expected["trace"]
    ]


def test_the_only_addition_to_a_successful_step_is_the_absent_failure() -> None:
    state = run_case(BASELINE_CASES[0])
    baseline_steps = load_baseline()[BASELINE_CASES[0]["name"]]["steps"]
    assert baseline_steps, "the frozen case must have taken at least one step"

    for index, step in enumerate(state.model_dump(mode="json")["steps"]):
        added = set(step) - set(baseline_steps[index])
        assert added <= set(ADDITIVE_STEP_KEYS)
        for key in added:
            assert step[key] is None, "a successful step carries no failure"


def test_the_baseline_covers_every_terminal_status_m2_could_produce() -> None:
    statuses = {run_case(case).status for case in BASELINE_CASES}

    assert statuses == {
        ResearchStatus.DONE,
        ResearchStatus.REFUSED,
        ResearchStatus.BUDGET_EXHAUSTED,
    }, "degraded is unreachable without a failing tool, which no baseline case has"


def test_the_baseline_covers_every_stop_reason_m2_could_produce() -> None:
    reasons = {run_case(case).stop_reason for case in BASELINE_CASES}

    assert reasons == {
        "evidence_sufficient",
        "no_evidence",
        "insufficient_evidence",
        "budget_spent",
    }
